django/myform/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'), # /articles/
    path('new/', views.new, name='new'), # /articles/new/
    path('<int:pk>/', views.detail, name='detail'), # /articles/1/, /articles/2/
    path('<int:pk>/edit/', views.edit, name='edit'), # /articles/1/edit/
    path('<int:pk>/like/', views.like, name='like'),
    path('search/', views.search, name='search'),
]

django/myform/myform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

# def root(request):
#     return redirect('articles:index')

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
    path('', lambda r: redirect('articles:index'), name='root')
]

django/myform/articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # 1:N (User:Article)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # Article을 작성한 User -> article.user
    # User가 작성한 모든 Article -> user.article_set.all()
    # M:N [Like] - User:Article
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    # Article에 좋아요 누른 모든 User -> article.like_users.all()
    # User가 좋아요 누른 모든 Article -> user.article_set.all() -> user.like_articles.all()


# Auth
# 1. Authetication (인증)
# 2. Authorization (권한)

django/myform/articles/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta: # Class에 대한 정보가 담긴 Class
        model = Article
        fields = ['title', 'content',]


# class ArticleForm(forms.Form):
#     title = forms.CharField(
#         max_length=10,
#         label='제목',
#         widget=forms.TextInput(
#             attrs={
#                 'class': 'title', # class="title"
#                 'placeholder': '제목을 입력하세요.', # placeholder="..."
#             }
#         )
#     )
#     content = forms.CharField(
#         label="내용",
#         widget=forms.Textarea(
#             attrs={
#                 'class': 'content',
#                 'rows': 5,
#                 'cols': 20,
#                 'placeholder': '내용을 입력하세요.',
#             }
#         )
#     )


# Form Class의 용도
# 1. Form Tag 만들기
# 2. Database에 Data 생성하기 위한 틀 제공

django/myform/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    article_list = Article.objects.all()
    # Pagination
    # 1. aritcles를 Paginator에 입력
    paginator = Paginator(article_list, 3)
    # 2. 몇번째 page를 보여줄건지 GET으로 가져옴
    page = request.GET.get('page')
    # 3. 해당하는 page의 articles만 뽑기
    articles = paginator.get_page(page)

    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

# def new(request):
#     if request.method == 'POST':
#         # 데이터베이스에 데이터 생성 (Form)
#         # 1. 넘어온 데이터를 받기
#         article_form = ArticleForm(request.POST)
#         # title = request.POST.get('title')
#         # content = request.POST.get('content')
#         # 2. 넘어온 데이터 검증
#         if article_form.is_valid():
#             title = article_form.cleaned_data.get('title')
#             content = article_form.cleaned_data.get('content')
#             # 3. 데이터베이스에 Article 만들기!
#             article = Article.objects.create(title=title, content=content)
#             # 4. redirect -> detail
#             return redirect('articles:detail', article.pk)
#     else:
#         article_form = ArticleForm()
#         # 폼을 보여줌
#         context = {
#             'article_form': article_form,
#         }
#         return render(request, 'articles/new.html', context)

@login_required
def new(request):
    if request.method == 'POST':
        # 데이터베이스에 데이터 생성 (ModelForm)
        # 1. 넘어온 데이터를 받기 (title, content)
        article_form = ArticleForm(request.POST)

        # 2. 넘어온 데이터 검증
        if article_form.is_valid():
            # 3. 데이터베이스에 Article 만들기!
            article = article_form.save(commit=False)
            # 3-1. user 정보 끼워넣기
            article.user = request.user
            article.save()

            # 4. redirect -> detail
            return redirect('articles:detail', article.pk)
    else:
        article_form = ArticleForm()

    # 폼을 보여줌
    context = {
        'article_form': article_form,
    }
    return render(request, 'articles/new.html', context)

def detail(request, pk):
    # 1. pk번째 데이터를 가져오기
    article = Article.objects.get(pk=pk)
    # 2. context로 넘겨주기
    context = {
        'article': article,
    }
    # 3. render와 함께 html로 넘겨주기
    return render(request, 'articles/detail.html', context)


# def edit(request, pk):
#     article = Article.objects.get(pk=pk)
#     if request.method == 'POST':
#         # Article 수정
#         # 1. 넘어온 데이터 받기
#         article_form = ArticleForm(request.POST)
#         # 2. 데이터 검증
#         if article_form.is_valid():
#             # 3. 검증된 데이터로 수정 & 저장
#             article.title = article_form.cleaned_data.get('title')
#             article.content = article_form.cleaned_data.get('content')
#             article.save()
#             # 4. redirect -> detail
#             return redirect('articles:detail', article.pk)
#     else:
#         # Article 수정하는 Form 보여주기
#         article_form = ArticleForm(
#                 {
#                     'title': article.title,
#                     'content': article.content,
#                 }
#             )
#         context = {
#             'article_form': article_form,
#         }
#         return render(request, 'articles/new.html', context)

@login_required
def edit(request, pk):
    article = Article.objects.get(pk=pk)
    # article의 주인인지 검증
    if request.user != article.user:
        return redirect('articles:index')

    if request.method == 'POST':
        # Article 수정
        # 1. 넘어온 데이터 받기
        article_form = ArticleForm(request.POST, instance=article)
        # 2. 데이터 검증
        if article_form.is_valid():
            # 3. 검증된 데이터로 수정 & 저장
            article_form.save()

            # 4. redirect -> detail
            return redirect('articles:detail', article.pk)
    else:
        # Article 수정하는 Form 보여주기
        article_form = ArticleForm(instance=article)

    context = {
        'article_form': article_form,
    }
    return render(request, 'articles/new.html', context)

# POST 요청만 받음
@login_required
def like(request, pk):
    # 1. pk번 article을 가져오기
    article = Article.objects.get(pk=pk)
    # 2. 현재 로그인한 user가 이 article에 좋아요를 눌렀는지?
    if request.user in article.like_users.all():
        # 3-1. 좋아요 취소
        article.like_users.remove(request.user)
    else:
        # 3-2. 좋아요
        article.like_users.add(request.user)

    return redirect('articles:detail', pk)

# GET 요청을 받음
def search(request):
    # 1. request로 부터 검색어 가져오기
    query = request.GET.get('query') #=> 'asdf'
    # 2. Article에서 제목에 검색어가 있는지 찾기
    articles = Article.objects.filter(title__contains=query)
    # 3. context로 결과값 template에 넘겨주기
    context = {
        'articles': articles,
    }

    return render(request, 'articles/search.html', context)

django/myform/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block body %}

<h1>Article Detail</h1>

<p>pk: {{ article.pk }}</p>
<p>user: {{ article.user.username }}</p>
<p>title: {{ article.title }}</p>
<p>content: {{ article.content }}</p>
<p>created at: {{ article.created_at }}</p>
<p>updated at: {{ article.updated_at }}</p>

<p>like: {{ article.like_users.count }}</p>

{% if user.is_authenticated %}
<form action="{% url 'articles:like' article.pk %}" method="POST">
    {% csrf_token %}
    {% if user in article.like_users.all %}
    <input type="submit" value="좋아요 취소">
    {% else %}
    <input type="submit" value="좋아요">
    {% endif %}
</form>
{% endif %}

<div>
    <a href="{% url 'articles:index' %}">List</a>
    {% if user == article.user %}
    <a href="{% url 'articles:edit' article.pk %}">Edit</a>
    {% endif %}
</div>

{% endblock %}

django/myform/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block body %}

<form action="{% url 'articles:search' %}" method="GET">
    <input type="text" name="query">
    <input type="submit" value="제목으로 검색!">
</form>

<h1>Article Index</h1>

{% if user.is_authenticated %}
<a href="{% url 'articles:new' %}">New Article</a>
{% endif %}

<ul>
    {% for article in articles %}
    <li>
        <a href="{% url 'articles:detail' article.pk %}">
            {{ article.title }}
        </a>
    </li>
    {% endfor %}
</ul>

<nav>
    <ul class="pagination">
        {% if articles.has_previous %}
        <li class="page-item">
            <a class="page-link" href="{% url 'articles:index' %}?page={{ articles.previous_page_number }}">Previous</a>
        </li>
        {% endif %}
        
        {% for num_page in articles.paginator.page_range %}
        <li class="page-item {% if num_page == articles.number %}active{% endif %}">
            <a class="page-link" href="{% url 'articles:index' %}?page={{ num_page }}">{{ num_page }}</a>
        </li>
        {% endfor %}

        {% if articles.has_next %}
        <li class="page-item">
            <a class="page-link" href="{% url 'articles:index' %}?page={{ articles.next_page_number }}">Next</a>
        </li>
        {% endif %}
    </ul>
</nav>


{% endblock %}

django/myform/articles/templates/articles/new.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}

<h1>Article Form</h1>

<form action="" method="POST">
    {% csrf_token %}
    <!-- <label for="">Title: </label>
    <input type="text" name="title">
    <label for="">Content: </label>
    <textarea name="content" id="" cols="30" rows="10"></textarea> -->
    {% bootstrap_form article_form %}
    {% buttons submit='작성하기' %}
        <!-- 추가 버튼 생성 가능 -->
    {% endbuttons %}
    <!-- <input type="submit"> -->
</form>

{% endblock %}

django/myform/articles/templates/articles/search.html
{% extends 'base.html' %}

{% block body %}

<h1>Search Result</h1>

<ul>
        {% for article in articles %}
        <li>
            <a href="{% url 'articles:detail' article.pk %}">
                {{ article.title }}
            </a>
        </li>
        {% endfor %}
    </ul>

{% endblock %}