django/crud_review/crud_review/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('students/', include('students.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/crud_review/students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path('', views.index, name='index'), # GET /students/
    path('new/', views.new, name='new'), # GET,POST /students/new/
    # path('create/', views.create, name='create'), # POST /students/create/ (x)
    path('<int:pk>/', views.detail, name='detail'), # GET /students/1/
    path('<int:pk>/edit/', views.edit, name='edit'), # GET,POST /students/1/edit/
    # path('<int:pk>/update/', views.update, name='update'), # POST /students/1/update/ (x)
    path('<int:pk>/delete/', views.delete, name='delete'), # POST /students/1/delete/
    path('<int:student_pk>/comments/new/', views.comments_new, name='comments_new'),
    path('<int:student_pk>/comments/<int:pk>/delete/', views.comments_delete, name='comments_delete'), # POST /students/1/comments/1/delete/
    path('<int:student_pk>/comments/<int:pk>/edit/', views.comments_edit, name='comments_edit'),
]

# URL Name -> 각각의 path
# path('주소/', views.함수, name='이름')
# {% url '이름' %} #=> 주소
# [장점]
# 1. 주소의 변경이 필요할 때, urls.py에서만 수정해주면 됨
# 2. 마지막 '/'를 빼먹는 실수를 차단할 수 있음

# App Name - 특정 app의 urls.py 자체
# {% url 'app_name:path_name' %} #=> 주소!


# RESTful
# 1. 자원(Resource) - URI
# 2. 행위(Verb) - HTTP Method (GET, POST, ...)
# 3. 표현(Representations) - 자원 + 행위

# Django는 PUT/PATCH/DELETE 불가능. 따라서...
# GET  /students/2/edit/ #=> 수정 페이지 보여줌
# POST /students/2/edit/ #=> 수정 작업 수행

# ex)
# GET     /users/1  #=> user 1번 가져옴
# PUT     /users/1  #=> user 1번 수정
# DELETE  /users/1  #=> user 1번 삭제

django/crud_review/students/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail, ResizeToFill, ResizeToFit
# Thumbnail(가로, 세로) - 썸네일
# ResizeToFill(300, 300) - 원본 비율 유지, 해상도를 넘어가는 부분 잘라냄
# ResizeToFit(300, 300) - 원본 비율 무시, 대신 모든 이미지가 보이도록 압축

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=10)
    age = models.IntegerField()
    image = ProcessedImageField(
        blank=True,
        upload_to='students/images', # 업로드 위치
        processors=[ResizeToFill(300, 300)], # 처리할 작업들 목록
        format='jpeg', # 저장 포멧 - jpg, png 등 사용 가능
        options={
            'quality': 90, # 옵션
        },
    )
    # image = models.ImageField(blank=True)
    # blank=True -> 비어 있는 값(ex. '')이 들어올 수 있음.
    # null=True -> None(NULL)이 들어올 수 있음.
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # 1. DB에 테이블을 생성하기 위한 설계도 생성
    # python manage.py makemigrations

    # 2. 설계도를 가지고 실제 DB에 테이블을 생성
    # python manage.py migrate

# Student : Comment = 1 : N
class Comment(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    # CASCADE - 1:N에서 1이 삭제되면 N도 삭제
    # PROTECT - 1을 삭제하려 할 때, N이 있으면 삭제 불가능
    # SET_NULL - 1이 삭제가 되면, N의 컬럼에 NULL로 설정
    # DO_NOTHING - 아무것도 하지 않음

    # 1. 1번 학생(1) 가져오기
    # student = Student.objects.get(pk=1)

    # 2. 댓글(N) 생성
    # comment = Comment()
    # comment.content = 'First Comment'
    # comment.student = student
    # (comment.student_id = student.pk)
    # comment.save()

    # 3. 댓글(N)로부터 학생(1) 불러오기
    # comment.student #=> student 인스턴스 자체
    # comment.student.name #=> 학생 이름
    # comment.student.age #=> 학생 나이

    # 4. 학생(1)으로부터 댓글(N) 불러오기
    # student.comment_set.all() #=> comment QuerySet

django/crud_review/students/views.py
from django.shortcuts import render, redirect
from .models import Student, Comment

# Create your views here.
def index(request):
    # 1. 모든 student를 DB에서 가져오기
    students = Student.objects.all()

    # 2. context에 저장
    context = {
        'students': students,
    }

    # 3. render하면서 context 넘겨주기
    return render(request, 'students/index.html', context)

def new(request):
    if request.method == 'POST': #=> 'GET', 'POST'
        # student를 생성함 (def create)
        # 1. POST 요청으로 넘어온 데이터 가져오기
        name = request.POST.get('name')
        age = request.POST.get('age')
        image = request.FILES.get('image')

        # 2. Model 클래스 사용해서 DB에 저장!
        student = Student(name=name, age=age, image=image)
        student.save()

        # 3. 생성된 학생의 상세 정보를 보는 페이지로 이동(Detail)
        return redirect('students:detail', student.pk)
    else:
        # new page를 보여주면 됨 (def new)
        return render(request, 'students/new.html')

    

# POST 요청을 받는 친구
# def create(request):
#     # 1. POST 요청으로 넘어온 데이터 가져오기
#     name = request.POST.get('name')
#     age = request.POST.get('age')

#     # 2. Model 클래스 사용해서 DB에 저장!
#     student = Student(name=name, age=age)
#     student.save()

#     # 3. 생성된 학생의 상세 정보를 보는 페이지로 이동(Detail)
#     return redirect('students:detail', student.pk)

def detail(request, pk):
    # 1. pk에 해당하는 student를 DB에서 가져오기
    student = Student.objects.get(pk=pk) #=> student 인스턴스
    # 1-1. student의 comment를 다 가져오기 (2번째 방법)
    comments = student.comment_set.all()
    # 1-2. comments의 갯수 가져오기
    # comments.count()

    # 2. context에 저장
    context = {
        'student': student,
        'comments': comments,
    }

    # 3. render하면서 context 넘겨주기
    return render(request, 'students/detail.html', context)


def edit(request, pk):
    # 1. pk에 해당하는 student를 DB에서 가져오기
    student = Student.objects.get(pk=pk)
    if request.method == 'POST':
        # student를 수정 (def update)
        # 2. POST 요청을 통해 넘어온 데이터 가져오기
        name = request.POST.get('name')
        age = request.POST.get('age')
        image = request.FILES.get('image')

        # 3. student 인스턴스의 정보를 변경 & DB에 반영 -> .save()
        student.name = name
        student.age = age
        if image:
            student.image = image
        student.save()

        # 4. student 상세 페이지로 이동(Detail)
        return redirect('students:detail', student.pk)
    else:
        # 수정하는 페이지를 보여줌 (def edit)
        # 2. context에 저장
        context = {
            'student': student,
        }

        # 3. render하면서 context 넘겨주기
        return render(request, 'students/edit.html', context)

# POST 요청만을 받음 -> redirect()
# def update(request, pk):
#     # 1. pk에 해당하는 student를 DB에서 가져오기
#     student = Student.objects.get(pk=pk)

#     # 2. POST 요청을 통해 넘어온 데이터 가져오기
#     name = request.POST.get('name')
#     age = request.POST.get('age')

#     # 3. student 인스턴스의 정보를 변경 & DB에 반영 -> .save()
#     student.name = name
#     student.age = age
#     student.save()

#     # 4. student 상세 페이지로 이동(Detail)
#     return redirect('students:detail', student.pk)

# POST 요청만을 받음 -> redirect()
def delete(request, pk):
    if request.method == 'POST':
        # 1. pk에 해당하는 student를 DB에서 가져오기
        student = Student.objects.get(pk=pk)

        # 2. student 삭제 (DB에서 삭제하기)
        student.delete()

        # 3. index 페이지로 이동
        return redirect('students:index')
    
    # return 없음! 오류!

# POST 요청을 받음 -> redirect
def comments_new(request, student_pk):
    # 1. request에서 데이터 가져오기
    content = request.POST.get('content')

    # 2. Comment 생성
    comment = Comment()
    comment.content = content
    comment.student_id = student_pk
    comment.save()
    
    # 3. student 상세 페이지로 redirect
    return redirect('students:detail', student_pk)

# POST 요청을 받음
def comments_delete(request, student_pk, pk):
    comment = Comment.objects.get(pk=pk)
    comment.delete()
    return redirect('students:detail', student_pk)


def comments_edit(request, student_pk, pk):
    comment = Comment.objects.get(pk=pk)
    if request.method == 'POST':
        # POST
        # 1. POST로 넘어온 데이터 가져오기
        content = request.POST.get('content')

        # 2. comment에 바꿔 넣기 & 저장
        comment.content = content
        comment.save()

        # 3. student 상세 페이지로 redirect
        return redirect('students:detail', student_pk)
    else:
        # GET
        context = {
            'comment': comment,
        }
        return render(request, 'students/comments_edit.html', context)

django/crud_review/students/templates/students/comments_edit.html
{% extends 'base.html' %}

{% block body %}

<h1>Edit Comment</h1>

<form action="" method="POST">
    {% csrf_token %}
    <textarea name="content" id="" cols="30" rows="5">{{ comment.content }}</textarea>
    <input type="submit">
</form>

{% endblock %}

django/crud_review/students/templates/students/detail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<h1>Student Detail</h1>

<h3>{{ student.name }}</h3>
<h4>{{ student.age }}</h4>
{% if student.image %}
<img src="{{ student.image.url }}" alt="">
{% else %}
<img src="{% static 'lisa.png' %}" alt="">
{% endif %}
<h5>{{ student.created_at }}</h5>
<h5>{{ student.updated_at }}</h5>

<a href="{% url 'students:index' %}">List</a>

<a href="{% url 'students:edit' student.pk %}">Edit</a>

<!-- a tag는 POST 요청을 보낼 수 없습니다. 그렇다면...? form tag! -->
<form action="{% url 'students:delete' student.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete">
</form>

<hr>

<!-- 갯수를 표현하는 1번째 방법(DTL) -->
<!-- <h4>댓글 목록 / 댓글 갯수: {{ comments|length }}</h4> -->
<!-- 갯수를 표현하는 2번째 방법(ORM) -->
<h4>댓글 목록 / 댓글 갯수: {{ comments.count }}</h4>

<!-- 1번째 방법. Comment 목록 -> student.comment_set.all (DTL) -->
<ul>
    {% for comment in comments %}
    <li>
        {{ comment.content }}
        <a href="{% url 'students:comments_edit' student.pk comment.pk %}">수정</a>
        <form action="{% url 'students:comments_delete' student.pk comment.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="삭제">
        </form>
    </li>
    {% empty %}
    <li>
        작성된 댓글이 없습니다 :(
    </li>
    {% endfor %}
</ul>

<!-- Comment 입력창 -->
<form action="{% url 'students:comments_new' student.pk %}" method="POST">
    {% csrf_token %}
    <label for="">Comment: </label>
    <textarea name="content" id="" cols="30" rows="5"></textarea>
    <input type="submit">
</form>


{% endblock %}

django/crud_review/students/templates/students/edit.html
{% extends 'base.html' %}

{% block body %}

<h1>Edit Student</h1>

<!-- {# url 'students:update' student.pk #} -->
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="">Name: </label>
    <input type="text" name="name" value="{{ student.name }}">
    <label for="">Age: </label>
    <input type="number" name="age" value="{{ student.age }}">
    <label for="">Image: </label>
    <input type="file" name="image" accept="image/*">
    <input type="submit">
</form>

{% endblock %}

django/crud_review/students/templates/students/index.html
{% extends 'base.html' %}

{% load static %}

{% block body %}

<h1>Student Index</h1>

<img src="{% static 'bart.png' %}" alt="">
<img src="{% static 'lisa.png' %}" alt="">

<a href="{% url 'students:new' %}">New</a>

<ul>
    {% for student in students %}
        <li>
            <a href="{% url 'students:detail' student.pk %}">{{ student.name }}</a>
        </li>
    {% endfor %}
</ul>

{% endblock %}

django/crud_review/students/templates/students/new.html
{% extends 'base.html' %}

{% block body %}

<h1>New Student</h1>

<!-- {# url 'students:create' #} -->
<!-- action에 값이 없으면, 자기 자신의 주소로 요청을 보냄 -->
<form action="" method="POST" enctype="multipart/form-data">
    <!-- 1. application/x-www-from-urlencoded -->
    <!-- 문자열만 전송(기본값) -->
    <!-- 2. multipart/form-data -->
    <!-- 바이너리(파일 및 이미지)도 전송 가능 -->
    <!-- 3. text/plain -->
    <!-- 인코딩 하지 않음. -->
    {% csrf_token %}
    <label for="">Name: </label>
    <input type="text" name="name">
    <label for="">Age: </label>
    <input type="number" name="age">
    <label for="">Image: </label>
    <input type="file" name="image" accept="image/*">
    <input type="submit">
</form>

{% endblock %}