django/pjt01/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

django/pjt01/pjt01/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

django/pjt01/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=30)
    title_en = models.CharField(max_length=40)
    audience = models.IntegerField() # 정수
    open_date = models.DateField()
    genre = models.CharField(max_length=20)
    watch_grade = models.CharField(max_length=20)
    score = models.FloatField() # 실수
    poster_url = models.TextField()
    description = models.TextField()

django/pjt01/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie

# Create your views here.
def index(request):
    # 1. 모든 Movie 가져오기
    movies = Movie.objects.all()

    # 2. context 생성
    context = {
        'movies': movies,
    }

    # 3. context와 함께 render하기
    return render(request, 'movies/index.html', context)

def new(request):
    if request.method == 'POST':
        # DB에 Create
        title = request.POST.get('title')
        title_en = request.POST.get('title_en')
        audience = request.POST.get('audience')
        open_date = request.POST.get('open_date')
        genre = request.POST.get('genre')
        watch_grade = request.POST.get('watch_grade')
        score = request.POST.get('score')
        poster_url = request.POST.get('poster_url')
        description = request.POST.get('description')

        movie = Movie.objects.create(
            title=title,
            title_en=title_en,
            audience=audience,
            open_date=open_date,
            genre=genre,
            watch_grade=watch_grade,
            score=score,
            poster_url=poster_url,
            description=description
        )

        return redirect('movies:detail', movie.pk)
        
    else:
        return render(request, 'movies/new.html')

def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    context = {
        'movie': movie,
    }
    return render(request, 'movies/detail.html', context)

def edit(request, pk):
    movie = Movie.objects.get(pk=pk)

    if request.method == 'POST':
        title = request.POST.get('title')
        title_en = request.POST.get('title_en')
        audience = request.POST.get('audience')
        open_date = request.POST.get('open_date')
        genre = request.POST.get('genre')
        watch_grade = request.POST.get('watch_grade')
        score = request.POST.get('score')
        poster_url = request.POST.get('poster_url')
        description = request.POST.get('description')

        movie.title = title
        movie.title_en = title_en
        movie.audience = audience
        movie.open_date = open_date
        movie.genre = genre
        movie.watch_grade = watch_grade
        movie.score = score
        movie.poster_url = poster_url
        movie.description = description
        movie.save()

        return redirect('movies:detail', movie.pk)
        
    else:
        context = {
            'movie': movie,
        }
        return render(request, 'movies/edit.html', context)

def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    movie.delete()
    return redirect('movies:index')

django/pjt01/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block body %}

<h1>Movie Detail</h1>

<img src="{{ movie.poster_url }}" alt="poster" width="300px">

<ul>
    <li><b>Title: </b>{{ movie.title }}</li>
    <li><b>Title En: </b>{{ movie.title_en }}</li>
    <li><b>Audience: </b>{{ movie.audience }}</li>
    <li><b>Open Date: </b>{{ movie.open_date }}</li>
    <li><b>Genre: </b>{{ movie.genre }}</li>
    <li><b>Watch Grade: </b>{{ movie.watch_grade }}</li>
    <li><b>Score: </b>{{ movie.score }}</li>
    <li><b>Description: </b>{{ movie.description }}</li>
</ul>

<a href="{% url 'movies:index' %}">목록</a>
<a href="{% url 'movies:edit' movie.pk %}">수정</a>
<a href="{% url 'movies:delete' movie.pk %}">삭제</a>

{% endblock %}

django/pjt01/movies/templates/movies/edit.html
{% extends 'base.html' %}

{% block body %}

<h1>Edit Movie</h1>

<form action="" method="POST">
    {% csrf_token %}
    <div>
        <label for="">Title: </label>
        <input type="text" name="title" value="{{ movie.title }}">
    </div>
    <div>
        <label for="">Title En: </label>
        <input type="text" name="title_en" value="{{ movie.title_en }}">
    </div>
    <div>
        <label for="">Audience: </label>
        <input type="number" name="audience" value="{{ movie.audience }}">
    </div>
    <div>
        <label for="">Open Date: </label>
        <input type="date" name="open_date" value="{{ movie.open_date|date:'Y-m-d' }}">
    </div>
    <div>
        <label for="">Genre: </label>
        <input type="text" name="genre" value="{{ movie.genre }}">
    </div>
    <div>
        <label for="">Watch Grade: </label>
        <input type="text" name="watch_grade" value="{{ movie.watch_grade }}">
    </div>
    <div>
        <label for="">Score: </label>
        <input type="number" name="score" step="0.01" min="0" max="10" value="{{ movie.score }}">
    </div>
    <div>
        <label for="">Poster URL: </label>
        <input type="text" name="poster_url" value="{{ movie.poster_url }}">
    </div>
    <div>
        <label for="">Description: </label>
        <textarea name="description">{{ movie.description }}</textarea>
    </div>
    <div>
        <input type="submit">
    </div>
</form>

{% endblock %}

django/pjt01/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block body %}

<h1>Movie Index</h1>

<a href="{% url 'movies:new' %}">새 영화 등록</a>

<ul>
    {% for movie in movies %}
    <li>
        <a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a> - {{ movie.score }}
    </li>
    {% endfor %}
</ul>

{% endblock %}

django/pjt01/movies/templates/movies/new.html
{% extends 'base.html' %}

{% block body %}

<h1>New Movie</h1>

<form action="" method="POST">
    {% csrf_token %}
    <div>
        <label for="">Title: </label>
        <input type="text" name="title">
    </div>
    <div>
        <label for="">Title En: </label>
        <input type="text" name="title_en">
    </div>
    <div>
        <label for="">Audience: </label>
        <input type="number" name="audience">
    </div>
    <div>
        <label for="">Open Date: </label>
        <input type="date" name="open_date">
    </div>
    <div>
        <label for="">Genre: </label>
        <input type="text" name="genre">
    </div>
    <div>
        <label for="">Watch Grade: </label>
        <input type="text" name="watch_grade">
    </div>
    <div>
        <label for="">Score: </label>
        <input type="number" name="score" step="0.01" min="0" max="10">
    </div>
    <div>
        <label for="">Poster URL: </label>
        <input type="text" name="poster_url">
    </div>
    <div>
        <label for="">Description: </label>
        <textarea name="description"></textarea>
    </div>
    <div>
        <input type="submit">
    </div>
</form>

{% endblock %}